<?xml version="1.0" encoding="utf-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
        "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="" lang="">
<head>
  <title>Test Results Report - All API Test Cases</title>
  <meta http-equiv="Content-Type" content="text/html;charset=utf-8" />
  <meta name="description" content="TestNG unit test results." />
  <link href="reportng.css" rel="stylesheet" type="text/css" />
    <script type="text/javascript" src="reportng.js"></script>
</head>
<body>
<h1>All API Test Cases</h1>
<p>
  Test duration: 8.746s
</p>



  <table class="resultsTable">
    <tr><th colspan="3" class="header failed">Failed Tests</th></tr>
          <tr>
        <td colspan="3" class="group">com.testcases.reqres.PostCall</td>
      </tr>
            
<tr>
  <td class="method">
                  <span class="description" title="This test case for get request">f</span>
      </td>
  <td class="duration">
    0.156s
  </td>
  <td class="result">
        
    
        

        <a href="javascript:toggleElement('exception-0', 'block')" title="Click to expand/collapse"><b>java.lang.AssertionError: expected [200] but found [404]</b></a><br />
    <div class="stackTrace" id="exception-0">
              org.testng.Assert.fail(Assert.java:96)<br />
              org.testng.Assert.failNotEquals(Assert.java:776)<br />
              org.testng.Assert.assertEqualsImpl(Assert.java:137)<br />
              org.testng.Assert.assertEquals(Assert.java:118)<br />
              org.testng.Assert.assertEquals(Assert.java:652)<br />
              org.testng.Assert.assertEquals(Assert.java:662)<br />
              com.core.BaseAssertion.verifyStatusCode(BaseAssertion.java:25)<br />
              com.testcases.reqres.PostCall.f(PostCall.java:26)<br />
              sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)<br />
              sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)<br />
              sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)<br />
              java.lang.reflect.Method.invoke(Unknown Source)<br />
              org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)<br />
              org.testng.internal.Invoker.invokeMethod(Invoker.java:580)<br />
              org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)<br />
              org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)<br />
              org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)<br />
              org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)<br />
              org.testng.TestRunner.privateRun(TestRunner.java:648)<br />
              org.testng.TestRunner.run(TestRunner.java:505)<br />
              org.testng.SuiteRunner.runTest(SuiteRunner.java:455)<br />
              org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)<br />
              org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)<br />
              org.testng.SuiteRunner.run(SuiteRunner.java:364)<br />
              org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)<br />
              org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)<br />
              org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)<br />
              org.testng.TestNG.runSuitesLocally(TestNG.java:1137)<br />
              org.testng.TestNG.runSuites(TestNG.java:1049)<br />
              org.testng.TestNG.run(TestNG.java:1017)<br />
              org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)<br />
              org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)<br />
              org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)<br />
                </div>
      </td>
</tr>
<tr>
  <td class="method">
                  <span class="description" title="this test case for post request">g</span>
      </td>
  <td class="duration">
    0.080s
  </td>
  <td class="result">
        
    
        

        <a href="javascript:toggleElement('exception-1', 'block')" title="Click to expand/collapse"><b>java.lang.AssertionError: expected [201] but found [404]</b></a><br />
    <div class="stackTrace" id="exception-1">
              org.testng.Assert.fail(Assert.java:96)<br />
              org.testng.Assert.failNotEquals(Assert.java:776)<br />
              org.testng.Assert.assertEqualsImpl(Assert.java:137)<br />
              org.testng.Assert.assertEquals(Assert.java:118)<br />
              org.testng.Assert.assertEquals(Assert.java:652)<br />
              org.testng.Assert.assertEquals(Assert.java:662)<br />
              com.core.BaseAssertion.verifyStatusCode(BaseAssertion.java:25)<br />
              com.testcases.reqres.PostCall.g(PostCall.java:38)<br />
              sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)<br />
              sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)<br />
              sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)<br />
              java.lang.reflect.Method.invoke(Unknown Source)<br />
              org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)<br />
              org.testng.internal.Invoker.invokeMethod(Invoker.java:580)<br />
              org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)<br />
              org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)<br />
              org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)<br />
              org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)<br />
              org.testng.TestRunner.privateRun(TestRunner.java:648)<br />
              org.testng.TestRunner.run(TestRunner.java:505)<br />
              org.testng.SuiteRunner.runTest(SuiteRunner.java:455)<br />
              org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)<br />
              org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)<br />
              org.testng.SuiteRunner.run(SuiteRunner.java:364)<br />
              org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)<br />
              org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)<br />
              org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)<br />
              org.testng.TestNG.runSuitesLocally(TestNG.java:1137)<br />
              org.testng.TestNG.runSuites(TestNG.java:1049)<br />
              org.testng.TestNG.run(TestNG.java:1017)<br />
              org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)<br />
              org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)<br />
              org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)<br />
                </div>
      </td>
</tr>
          <tr>
        <td colspan="3" class="group">com.testcases.reqres.SuccessAuthetication</td>
      </tr>
            
<tr>
  <td class="method">
                  <span class="description" title="this test case for post request with correct credential and verify is it creating token or not">successFul</span>
      </td>
  <td class="duration">
    0.078s
  </td>
  <td class="result">
        
    
        

        <a href="javascript:toggleElement('exception-2', 'block')" title="Click to expand/collapse"><b>java.lang.AssertionError: expected [201] but found [404]</b></a><br />
    <div class="stackTrace" id="exception-2">
              org.testng.Assert.fail(Assert.java:96)<br />
              org.testng.Assert.failNotEquals(Assert.java:776)<br />
              org.testng.Assert.assertEqualsImpl(Assert.java:137)<br />
              org.testng.Assert.assertEquals(Assert.java:118)<br />
              org.testng.Assert.assertEquals(Assert.java:652)<br />
              org.testng.Assert.assertEquals(Assert.java:662)<br />
              com.core.BaseAssertion.verifyStatusCode(BaseAssertion.java:25)<br />
              com.testcases.reqres.SuccessAuthetication.successFul(SuccessAuthetication.java:23)<br />
              sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)<br />
              sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)<br />
              sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)<br />
              java.lang.reflect.Method.invoke(Unknown Source)<br />
              org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)<br />
              org.testng.internal.Invoker.invokeMethod(Invoker.java:580)<br />
              org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)<br />
              org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)<br />
              org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)<br />
              org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)<br />
              org.testng.TestRunner.privateRun(TestRunner.java:648)<br />
              org.testng.TestRunner.run(TestRunner.java:505)<br />
              org.testng.SuiteRunner.runTest(SuiteRunner.java:455)<br />
              org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)<br />
              org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)<br />
              org.testng.SuiteRunner.run(SuiteRunner.java:364)<br />
              org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)<br />
              org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)<br />
              org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)<br />
              org.testng.TestNG.runSuitesLocally(TestNG.java:1137)<br />
              org.testng.TestNG.runSuites(TestNG.java:1049)<br />
              org.testng.TestNG.run(TestNG.java:1017)<br />
              org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)<br />
              org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)<br />
              org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)<br />
                </div>
      </td>
</tr>
<tr>
  <td class="method">
                  <span class="description" title="this test case for post request with incorrect credential and verify is it sending error message or not">unSuccessFul</span>
      </td>
  <td class="duration">
    0.066s
  </td>
  <td class="result">
        
    
        

        <a href="javascript:toggleElement('exception-3', 'block')" title="Click to expand/collapse"><b>java.lang.AssertionError: expected [400] but found [404]</b></a><br />
    <div class="stackTrace" id="exception-3">
              org.testng.Assert.fail(Assert.java:96)<br />
              org.testng.Assert.failNotEquals(Assert.java:776)<br />
              org.testng.Assert.assertEqualsImpl(Assert.java:137)<br />
              org.testng.Assert.assertEquals(Assert.java:118)<br />
              org.testng.Assert.assertEquals(Assert.java:652)<br />
              org.testng.Assert.assertEquals(Assert.java:662)<br />
              com.core.BaseAssertion.verifyStatusCode(BaseAssertion.java:25)<br />
              com.testcases.reqres.SuccessAuthetication.unSuccessFul(SuccessAuthetication.java:35)<br />
              sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)<br />
              sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)<br />
              sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)<br />
              java.lang.reflect.Method.invoke(Unknown Source)<br />
              org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)<br />
              org.testng.internal.Invoker.invokeMethod(Invoker.java:580)<br />
              org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)<br />
              org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)<br />
              org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)<br />
              org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)<br />
              org.testng.TestRunner.privateRun(TestRunner.java:648)<br />
              org.testng.TestRunner.run(TestRunner.java:505)<br />
              org.testng.SuiteRunner.runTest(SuiteRunner.java:455)<br />
              org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)<br />
              org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)<br />
              org.testng.SuiteRunner.run(SuiteRunner.java:364)<br />
              org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)<br />
              org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)<br />
              org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)<br />
              org.testng.TestNG.runSuitesLocally(TestNG.java:1137)<br />
              org.testng.TestNG.runSuites(TestNG.java:1049)<br />
              org.testng.TestNG.run(TestNG.java:1017)<br />
              org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)<br />
              org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)<br />
              org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)<br />
                </div>
      </td>
</tr>
      </table>


  <table class="resultsTable">
    <tr><th colspan="3" class="header passed">Passed Tests</th></tr>
          <tr>
        <td colspan="3" class="group">com.testcases.reqres.SimpleDelete</td>
      </tr>
            
<tr>
  <td class="method">
                  <span class="description" title="This test case for validate delete resource">validateDelete</span>
      </td>
  <td class="duration">
    3.634s
  </td>
  <td class="result">
        
    
        

      </td>
</tr>
          <tr>
        <td colspan="3" class="group">com.testcases.reqres.SimpleGetNotFound</td>
      </tr>
            
<tr>
  <td class="method">
                  <span class="description" title="This test case not found the resource">GetWeatherDetails</span>
      </td>
  <td class="duration">
    0.693s
  </td>
  <td class="result">
        
    
        

      </td>
</tr>
          <tr>
        <td colspan="3" class="group">com.testcases.reqres.SimpleGetTest</td>
      </tr>
            
<tr>
  <td class="method">
                  <span class="description" title="This test case for validate the get resource">GetWeatherDetails</span>
      </td>
  <td class="duration">
    0.660s
  </td>
  <td class="result">
        
    
        

      </td>
</tr>
          <tr>
        <td colspan="3" class="group">com.testcases.reqres.SimplePostTest</td>
      </tr>
            
<tr>
  <td class="method">
                  <span class="description" title="This test case for validate post call">GetWeatherDetails</span>
      </td>
  <td class="duration">
    1.322s
  </td>
  <td class="result">
        
    
        

      </td>
</tr>
          <tr>
        <td colspan="3" class="group">com.testcases.reqres.SimplePutTest</td>
      </tr>
            
<tr>
  <td class="method">
                  <span class="description" title="This test case for validate put configuration">validateDelete</span>
      </td>
  <td class="duration">
    0.673s
  </td>
  <td class="result">
        
    
        

      </td>
</tr>
          <tr>
        <td colspan="3" class="group">com.testcases.reqres.UnthenticationSuccessful</td>
      </tr>
            
<tr>
  <td class="method">
                  <span class="description" title="this test vaildate the suceessful authentication">validateSuccessful</span>
      </td>
  <td class="duration">
    0.695s
  </td>
  <td class="result">
        
    
        

      </td>
</tr>
          <tr>
        <td colspan="3" class="group">com.testcases.reqres.UnthenticationUnSuccessful</td>
      </tr>
            
<tr>
  <td class="method">
                  <span class="description" title="This test case valiadate the unsuceessful attempt">validateUnsuccessful</span>
      </td>
  <td class="duration">
    0.689s
  </td>
  <td class="result">
        
    
        

      </td>
</tr>
      </table>
  
</body>
</html>
